org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true

neoforge_version=21.1.234
parchment_mc=1.21.1
parchment_version=2024.11.17

mod_id=fancy_trail
mod_name=Fancy Trail
mod_license=All Rights Reserved
mod_version=1.2.6-port1
mod_group_id=com.inspiration_mushroom.fancy_trail
mod_authors=Inspiration Mushroom(GuHao_)
mod_description=Cool mod.
